### ISSUE TITLE
建议~

### ISSUE THREAD

**Issue by hongyangAndroid** [Sunzxyong/ApiInspect#1]
很nice的库，实现方案非常赞，不过有一点困惑 ~

发现检测的时候，做了一个getPackageFromBuildConfig的过滤。

这样的话，貌似不包含BuildConfig.class的jar包，里面也存在不兼容的地方就无法检测到了。

想请问下是考虑的出发点是？

或者可以添加配置选项，让用户去选择控制是否更好？

**Comment by Sunzxyong** [comment]
@hongyangAndroid 多谢鸿洋哥~
getPackageFromBuildConfig方法主要是获取对应jar的包名，通过此包名匹配来进行过滤，不是不包含BuildConfig.class的jar包。

可能不同业务方有一些aar、jar库不需要检测（如：google zxing库等），在build.gradle配置属性：
`apiInspect {
       exclude {
       }
}` 域下，业务方可以**exclude**不需要检测的SDK，传入的值为包名，而上面的getPackageFromBuildConfig正是与业务方设置的包名进行匹配过滤。
